name: Build OBS GameDetector (Windows)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Instalar Inno Setup
    - name: Install Inno Setup
      run: |
        curl -L -o innosetup.exe https://files.jrsoftware.org/is/6/innosetup-6.6.0.exe
        .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART

    # Configurar CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    # Compilar plugin
    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    # Criar ou atualizar a Release
    - name: Create or Update Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: OBSGameDetector
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    # Upload do ZIP para a Release
    - name: Upload ZIP to Release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        files: setup/OBSGameDetector.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    # Upload do Installer para a Release
    - name: Upload Installer to Release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        files: setup/OBSGameDetector-Setup.exe
        token: ${{ secrets.GITHUB_TOKEN }}
