name: Build OBS GameDetector (Windows)

on:
  push:
    tags:
      - "v*"      # exemplo: v1.0.0
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Instalar Inno Setup
    - name: Install Inno Setup
      run: |
        curl -L -o innosetup.exe https://files.jrsoftware.org/is/6/innosetup-6.6.0.exe
        .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART

    # Configurar CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    # Compilar plugin
    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    # Criar ou atualizar a Release
    - name: Create or Update Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    # Upload do ZIP para a Release
    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: setup/OBSGameDetector.zip
        asset_name: OBSGameDetector.zip
        asset_content_type: application/zip

    # Upload do Installer para a Release
    - name: Upload Installer to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: setup/OBSGameDetector-Setup.exe
        asset_name: OBSGameDetector-Setup.exe
        asset_content_type: application/zip
